### PR TITLE
#44 fix by setting empty data fields when length(data)==0

### LINKED ISSUE #44: Errors when empty data present in mat file
I occasionally encounter .mat files saved from an instrument (powerlab) where the header contains information, but the data field is null.  readMat fails in those cases but can be rescued with a check for null data before converting to matrix for both character and text data types.  

Would it be possible to add in these two checks for empty data and set data = "" if character type, and NA if numeric?  This would happen at lines 1082 and 1098 in readMat.R

If possible, also add an explicit conversion to matrix before 1082 because sometimes I'm getting a character string that fails at the dim() call unless data is first converted to matrix.

### PR DESCRIPTION
**Pull request by gordon-turner**
RESOLVES #44 

These files arise from instruments that write to .mat file format.  I do not have an example to share for creating a test, but the minimal changes included here make it possible to read these files without error.

### CODE REVIEW

**Comment by gordon-turner** [comment]
Thanks @HenrikBengtsson  - I made the suggested changes. Please let me know if there is anything else I need to do.

File: tests/readMat.R [hunk 1]
```diff
@@ -221,3 +224,21 @@ stopifnot(
...
+
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Reading ADI LabChart export example file
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+pathname <- file.path(path, "ADI_LabChart_Export.mat")
+
+cat("Reading ADI Labchart file: ", basename(pathname), "\n", sep = "")
+tryCatch({
```
Comment (HenrikBengtsson) [inline tests/readMat.R:236]: One more thing. So, here you don't want to use `tryCatch()`, because you want this test to fail if `readMat()` fails.  So, just do:

```r
mat <- readMat(pathname)
print(mat)
```

You could also add some assertions that the read data is what you'd expect, e.g.

```r
stopifnot(
  length(mat) == 14,
  identical(dim(mat$data), c(1L, 4360L)),
  identical(mat$comtext, character(0))
)
```

Comment (HenrikBengtsson) [inline tests/readMat.R:236]: One more thing. So, here you don't want to use `tryCatch()`, because you want this test to fail if `readMat()` fails.  So, just do:

```r
mat <- readMat(pathname)
print(mat)
```

You could also add some assertions that the data read is what you'd expect, e.g.

```r
stopifnot(
  length(mat) == 14,
  identical(dim(mat$data), c(1L, 4360L)),
  identical(mat$comtext, character(0)),
  identical(dim(mat$com), c(0L, 5L))
)
```

assuming the latter two are the ones solved by this PR (correct?)

File: tests/readMat.R [hunk 2]
```diff
@@ -221,3 +224,21 @@ stopifnot(
   inherits(res, "error"),
   grepl("MAT v7.3 files is not supported", conditionMessage(res))
 )
+
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```
Comment (HenrikBengtsson) [inline tests/readMat.R:229]: Please make the comment information on what we're testing here, e.g.

```
# Assert that we call read data fields with empty dimensions
```

File: tests/readMat.R (hunk 1 above)
Comment (HenrikBengtsson) [reply tests/readMat.R:236]: BTW, using

```r
str(mat)
```

is probably better, since some of the elements are quite large.

**Comment by HenrikBengtsson** [comment]
Thank you! It's been merged.

**Comment by gordon-turner** [comment]
> Thank you! It's been merged.

Thank you for all your help with the process!
